/* KirthiVerse Controlled Pilot Run v1 — route /pilot-run
   P5 lifecycle that can start ONLY after the P4 owner-attested readiness gate evaluates READY.
   This remains local-only. It does not verify guardian identity, legal consent, external review quality,
   safeguarding approval, research ethics, school approval, or production readiness. */
(()=>{
  const KEY='kirthiverse.hitech.pilot.run.v1';
  const METRICS_KEY='kirthiverse.hitech.pilot.metrics.v1';
  const GATE_KEY='kirthiverse.hitech.parentgate.v1';
  const UNLOCK_KEY='kirthiverse.hitech.parentgate.unlocked.v1';
  const PREFIX='kirthiverse.hitech.';
  const ACK='I am the adult operating this device for the controlled pilot. I understand the app only records the P4 owner-attested readiness state and does not independently verify external approvals, identity, or legal consent.';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const clone=x=>JSON.parse(JSON.stringify(x));
  const read=(k,f)=>{try{const raw=localStorage.getItem(k);return raw===null?clone(f):JSON.parse(raw)}catch{return clone(f)}};
  const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
  const now=()=>new Date().toISOString();
  const unlocked=()=>sessionStorage.getItem(UNLOCK_KEY)==='1';
  const uid=()=>crypto.randomUUID?.()||`run-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
  const run=()=>read(KEY,null);
  const readiness=()=>window.KV_PILOT_READINESS?.evaluate?.()||{ready:false,status:'HOLD',missing:['readinessRuntime'],unchecked:[],metricsAvailable:Boolean(window.KV_PILOT_METRICS),legalCertification:false,productionReady:false,externalReviewSelfVerified:false};
  const readinessState=()=>window.KV_PILOT_READINESS?.state?.()||null;
  const metrics=()=>window.KV_PILOT_METRICS?.summary?.()||null;
  const gate=()=>read(GATE_KEY,{});
  function setAssistance(enabled){const g=gate();g.assistanceEnabled=Boolean(enabled);save(GATE_KEY,g);dispatchEvent(new CustomEvent('kv:assistance',{detail:{enabled:g.assistanceEnabled}}));}
  function snapshotReadiness(){return {capturedAt:now(),evaluation:clone(readiness()),record:clone(readinessState())};}
  function publicRun(s=run()){if(!s)return null;return {schema:s.schema,status:s.status,runId:s.runId,alias:s.alias,targetEndDate:s.targetEndDate||null,startedAt:s.startedAt||null,endedAt:s.endedAt||null,operatorAcknowledgement:s.operatorAcknowledgement||null,assistanceEnabledAtStart:Boolean(s.assistanceEnabledAtStart),readinessAtStart:s.readinessAtStart||null,readinessAtEnd:s.readinessAtEnd||null,finalSummary:s.finalSummary||null};}
  function evidenceBundle(){return {schema:'kirthiverse.hitech.controlled-pilot-run-evidence.v1',exportedAt:now(),run:publicRun(),currentReadiness:snapshotReadiness(),currentMetrics:metrics(),evidenceBoundary:{localOnly:true,adultIdentityVerified:false,legalConsentVerified:false,externalReviewIndependentlyVerified:false,tamperEvident:false,auditedResearchEvidence:false,productionReady:false}};}
  function download(payload,name){const b=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),0)}

  function parentLocked(){return `<div class="page run-page"><div class="page-title"><span>P5 // CONTROLLED PILOT RUN</span><h1>Unlock Parent Space first</h1><p>The run lifecycle is a grown-up control on this browser.</p></div><a class="primary" data-link href="/parent">Open Parent Space →</a></div>`;}
  function readinessHold(e){return `<div class="page run-page"><div class="page-title"><span>P5 // CONTROLLED PILOT RUN</span><h1>Readiness gate is HOLD</h1><p>P5 cannot start until the P4 readiness record evaluates READY. Missing: ${esc([...(e.missing||[]),...(e.unchecked||[])].join(', ')||'readiness evidence')}.</p></div><a class="primary" data-link href="/pilot-readiness">Complete P4 readiness →</a><section class="glass-card"><small class="kicker">EVIDENCE BOUNDARY</small><p>This block is intentional. P5 does not infer or fabricate external approvals.</p></section></div>`;}
  function setup(){return `<div class="page run-page"><div class="page-title"><span>P5 // READY-GATED PILOT</span><h1>Start controlled observation</h1><p>P4 is currently owner-attested READY. Starting this run freezes a copy of that readiness record and begins a fresh local metrics observation window.</p></div><form id="run-start" class="run-form glass-card"><label>Pilot learner alias<input id="run-alias" maxlength="30" required placeholder="Alias only"></label><label>Optional target end date<input id="run-target" type="date"></label><label class="run-check"><input id="run-ack" type="checkbox" required><span>${esc(ACK)}</span></label><label class="run-check"><input id="run-assist" type="checkbox"><span>Allow bounded hints/worked guidance during this run. Default OFF. No live AI tutor exists in this build.</span></label><button class="primary" type="submit">Start controlled run</button><p id="run-msg" class="run-note" role="status" aria-live="polite"></p></form>${dataControls()}</div>`;}
  function active(s){const w=metrics(),e=readiness(),ok=e.ready===true;return `<div class="page run-page"><div class="page-title"><span>P5 // RUN ACTIVE</span><h1>${esc(s.alias)}</h1><p>Started ${esc(new Date(s.startedAt).toLocaleString())}${s.targetEndDate?` · target ${esc(s.targetEndDate)}`:''}.</p></div><section id="run-current-readiness" class="run-status ${ok?'run-go':'run-hold'}"><small>CURRENT P4 GATE</small><h2>${ok?'READY':'HOLD — PAUSE PILOT'}</h2><p>${ok?'Current owner-attested prerequisites remain present.':'The readiness record changed after this run began. Do not continue the pilot until the P4 gate is restored.'}</p></section><section class="run-grid"><article class="glass-card"><small class="kicker">OBSERVATION</small><h2>${w?.observationDays??'—'} day${w?.observationDays===1?'':'s'}</h2><p>${w?.completeSevenDayWindow?'Seven-day window available.':'No seven-day retention claim yet.'}</p></article><article class="glass-card"><small class="kicker">ACTIVE LEARNING</small><h2>${w?.activeMinutes??'—'} min</h2><p>Conservative P3 measurement only.</p></article><article class="glass-card"><small class="kicker">ASSISTANCE AT START</small><h2>${s.assistanceEnabledAtStart?'ON':'OFF'}</h2><p>Bounded hints/worked guidance only.</p></article></section><section class="glass-card"><div class="run-actions"><a class="primary" data-link href="/weekly-report">Weekly report →</a><button id="run-export">Export evidence</button><button id="run-end">End &amp; freeze run</button></div><p id="run-msg" class="run-note" role="status" aria-live="polite"></p></section>${dataControls()}</div>`;}
  function ended(s){const f=s.finalSummary?.metrics;return `<div class="page run-page"><div class="page-title"><span>P5 // RUN ENDED</span><h1>${esc(s.alias)}</h1><p>Ended ${esc(new Date(s.endedAt).toLocaleString())}. The final snapshot remains local and is not tamper-evident/audited analytics.</p></div><section class="run-grid"><article class="glass-card"><small class="kicker">OBSERVATION DAYS</small><h2>${f?.observationDays??'—'}</h2></article><article class="glass-card"><small class="kicker">ACTIVE MINUTES</small><h2>${f?.activeMinutes??'—'}</h2></article><article class="glass-card"><small class="kicker">LESSONS COMPLETED</small><h2>${f?.uniqueLessonsCompleted??'—'}</h2></article></section><section class="glass-card"><div class="run-actions"><button id="run-export">Export final evidence</button><a class="primary" data-link href="/pilot-readiness">P4 readiness record →</a></div></section>${dataControls()}</div>`;}
  function dataControls(){return `<section class="glass-card run-danger"><small class="kicker">LOCAL DATA CONTROLS</small><p>Run reset removes only the P5 run and P3 metrics observation; the P4 readiness record, Parent Space, educator plan and ordinary learning progress stay intact.</p><div class="run-actions"><button id="run-reset">Reset run + observation</button></div><label>Type <b>DELETE LOCAL DATA</b> for full KirthiVerse browser-data deletion<input id="run-delete-confirm" autocomplete="off"></label><button id="run-delete" disabled>Delete all KirthiVerse local data</button><p id="run-delete-msg" class="run-note" role="status" aria-live="polite"></p></section>`;}

  function startRun(ev){ev.preventDefault();const msg=document.getElementById('run-msg'),e=readiness();if(!e.ready){msg.textContent='P4 readiness is no longer READY.';render();return}const alias=document.getElementById('run-alias').value.trim(),target=document.getElementById('run-target').value||null,ack=document.getElementById('run-ack').checked,assist=document.getElementById('run-assist').checked;if(!alias){msg.textContent='Enter a learner alias.';return}if(!ack){msg.textContent='Operator acknowledgement is required.';return}if(target&&target<new Date().toISOString().slice(0,10)){msg.textContent='Target end date cannot be in the past.';return}localStorage.removeItem(METRICS_KEY);window.KV_PILOT_METRICS?.sync?.();const startedAt=now(),s={schema:'kirthiverse.hitech.pilot-run.v1',status:'active',runId:uid(),alias:alias.slice(0,30),targetEndDate:target,startedAt,endedAt:null,operatorAcknowledgement:{statement:ACK,acknowledgedAt:startedAt,mode:'self-attestation',adultIdentityVerified:false,legalConsentVerified:false},assistanceEnabledAtStart:Boolean(assist),readinessAtStart:snapshotReadiness(),readinessAtEnd:null,finalSummary:null};save(KEY,s);setAssistance(assist);dispatchEvent(new CustomEvent('kv:pilot-run-started',{detail:{runId:s.runId,startedAt}}));render();}
  function endRun(){const s=run();if(!s||s.status!=='active')return;window.KV_PILOT_METRICS?.sync?.();const endedAt=now();s.status='ended';s.endedAt=endedAt;s.readinessAtEnd=snapshotReadiness();s.finalSummary={capturedAt:endedAt,metrics:metrics(),readiness:s.readinessAtEnd,evidenceBoundary:{localOnly:true,tamperEvident:false,auditedResearchEvidence:false}};save(KEY,s);dispatchEvent(new CustomEvent('kv:pilot-run-ended',{detail:{runId:s.runId,endedAt}}));render();}
  function resetRun(){if(!confirm('Reset only the P5 run and P3 observation data? P4 readiness and ordinary learning evidence remain.'))return;[KEY,METRICS_KEY].forEach(k=>localStorage.removeItem(k));render();}
  function deleteAll(){const input=document.getElementById('run-delete-confirm'),msg=document.getElementById('run-delete-msg');if(input?.value!=='DELETE LOCAL DATA'){msg.textContent='Type the exact confirmation phrase.';return}if(!confirm('Delete all KirthiVerse local data in this browser? This cannot be undone.'))return;const lk=[];for(let i=0;i<localStorage.length;i++)lk.push(localStorage.key(i));lk.filter(Boolean).filter(k=>k.startsWith(PREFIX)).forEach(k=>localStorage.removeItem(k));const sk=[];for(let i=0;i<sessionStorage.length;i++)sk.push(sessionStorage.key(i));sk.filter(Boolean).filter(k=>k.startsWith(PREFIX)).forEach(k=>sessionStorage.removeItem(k));history.replaceState({},'', '/');location.reload();}
  function bind(){document.getElementById('run-start')?.addEventListener('submit',startRun);document.getElementById('run-export')?.addEventListener('click',()=>download(evidenceBundle(),'kirthiverse-controlled-pilot-run-evidence.json'));document.getElementById('run-end')?.addEventListener('click',endRun);document.getElementById('run-reset')?.addEventListener('click',resetRun);const i=document.getElementById('run-delete-confirm'),b=document.getElementById('run-delete');i?.addEventListener('input',()=>{b.disabled=i.value!=='DELETE LOCAL DATA'});b?.addEventListener('click',deleteAll)}
  function injectCards(){if(location.pathname==='/parent'&&unlocked()){const main=document.querySelector('main');if(main&&!main.querySelector('.run-parent-card')){const s=run(),e=readiness(),c=document.createElement('section');c.className='glass-card run-parent-card';c.innerHTML=`<small class="kicker">CONTROLLED PILOT RUN</small><h3>${s?.status==='active'?'Run active':s?.status==='ended'?'Run ended':e.ready?'Ready to start':'Blocked by P4 HOLD'}</h3><p>${e.ready?'P4 prerequisites are owner-attested READY.':'Complete/restore P4 readiness before a new run can start.'}</p><a class="primary" data-link href="/pilot-run">Open controlled run →</a>`;main.appendChild(c)}}if(location.pathname==='/pilot-readiness'&&unlocked()&&readiness().ready){const main=document.querySelector('main');if(main&&!main.querySelector('.run-readiness-card')){const c=document.createElement('section');c.className='glass-card run-readiness-card run-go';c.innerHTML='<small class="kicker">NEXT GATE</small><h3>P4 owner-attested READY</h3><p>P5 can now start a fresh controlled observation window.</p><a class="primary" data-link href="/pilot-run">Open P5 controlled run →</a>';main.appendChild(c)}}}
  function render(){injectCards();if(location.pathname!=='/pilot-run')return;const main=document.querySelector('main');if(!main)return;if(!unlocked()){main.innerHTML=parentLocked();return}const s=run(),e=readiness();main.innerHTML=!s?(e.ready?setup():readinessHold(e)):s.status==='active'?active(s):ended(s);bind()}
  addEventListener('kv:rendered',()=>queueMicrotask(render));render();
  window.KV_PILOT_RUN={version:'v1',route:'/pilot-run',localOnly:true,requiresReadiness:true,adultIdentityVerified:false,legalConsentVerified:false,externalReviewIndependentlyVerified:false,productionReady:false,state:()=>publicRun(),evidence:evidenceBundle};
})();