/* KirthiVerse Controlled Pilot Run v1 — route /pilot-run
   P5 starts ONLY after the P4 owner-attested readiness gate evaluates READY.
   Local-only; no verified guardian identity, legal consent, external-review certification, or production-readiness claim. */
(()=>{
const KEY='kirthiverse.hitech.pilot.run.v1',METRICS='kirthiverse.hitech.pilot.metrics.v1',GATE='kirthiverse.hitech.parentgate.v1',UNLOCK='kirthiverse.hitech.parentgate.unlocked.v1',PREFIX='kirthiverse.hitech.';
const ACK='I am the adult operating this device for the controlled pilot. I understand the app only records the P4 owner-attested readiness state and does not independently verify external approvals, identity, or legal consent.';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),clone=x=>JSON.parse(JSON.stringify(x)),read=(k,f)=>{try{const r=localStorage.getItem(k);return r===null?clone(f):JSON.parse(r)}catch{return clone(f)}},save=(k,v)=>localStorage.setItem(k,JSON.stringify(v)),now=()=>new Date().toISOString(),unlocked=()=>sessionStorage.getItem(UNLOCK)==='1',uid=()=>crypto.randomUUID?.()||`run-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const run=()=>read(KEY,null),readiness=()=>window.KV_PILOT_READINESS?.evaluate?.()||{ready:false,status:'HOLD',missing:['readinessRuntime'],unchecked:[],legalCertification:false,productionReady:false,externalReviewSelfVerified:false},readinessState=()=>window.KV_PILOT_READINESS?.state?.()||null,metrics=()=>window.KV_PILOT_METRICS?.summary?.()||null;
const snapshotReadiness=()=>({capturedAt:now(),evaluation:clone(readiness()),record:clone(readinessState())});
function setAssistance(enabled){const g=read(GATE,{});g.assistanceEnabled=Boolean(enabled);save(GATE,g);dispatchEvent(new CustomEvent('kv:assistance',{detail:{enabled:g.assistanceEnabled}}))}
function publicRun(s=run()){return s?{schema:s.schema,status:s.status,runId:s.runId,alias:s.alias,targetEndDate:s.targetEndDate||null,startedAt:s.startedAt||null,endedAt:s.endedAt||null,operatorAcknowledgement:s.operatorAcknowledgement||null,assistanceEnabledAtStart:Boolean(s.assistanceEnabledAtStart),readinessAtStart:s.readinessAtStart||null,readinessAtEnd:s.readinessAtEnd||null,finalSummary:s.finalSummary||null}:null}
function evidence(){return{schema:'kirthiverse.hitech.controlled-pilot-run-evidence.v1',exportedAt:now(),run:publicRun(),currentReadiness:snapshotReadiness(),currentMetrics:metrics(),evidenceBoundary:{localOnly:true,adultIdentityVerified:false,legalConsentVerified:false,externalReviewIndependentlyVerified:false,tamperEvident:false,auditedResearchEvidence:false,productionReady:false}}}
function download(p,n){const b=new Blob([JSON.stringify(p,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=n;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),0)}
const controls=()=>`<section class="glass-card run-danger"><small class="kicker">LOCAL DATA CONTROLS</small><p>Run reset removes only P5 run + P3 observation. P4 readiness, Parent Space, educator plan and ordinary learning progress remain.</p><div class="run-actions"><button id="run-reset">Reset run + observation</button></div><label>Type <b>DELETE LOCAL DATA</b> for full KirthiVerse browser-data deletion<input id="run-delete-confirm" autocomplete="off"></label><button id="run-delete" disabled>Delete all KirthiVerse local data</button><p id="run-delete-msg" class="run-note" role="status" aria-live="polite"></p></section>`;
const parentLocked=()=>`<div class="page run-page"><div class="page-title"><span>P5 // CONTROLLED PILOT RUN</span><h1>Unlock Parent Space first</h1><p>The run lifecycle is a grown-up control on this browser.</p></div><a class="primary" data-link href="/parent">Open Parent Space →</a></div>`;
const hold=e=>`<div class="page run-page"><div class="page-title"><span>P5 // CONTROLLED PILOT RUN</span><h1>Readiness gate is HOLD</h1><p>P5 cannot start until P4 is READY. Missing: ${esc([...(e.missing||[]),...(e.unchecked||[])].join(', ')||'readiness evidence')}.</p></div><a class="primary" data-link href="/pilot-readiness">Complete P4 readiness →</a><section class="glass-card"><small class="kicker">EVIDENCE BOUNDARY</small><p>P5 does not infer or fabricate external approvals.</p></section></div>`;
const setup=()=>`<div class="page run-page"><div class="page-title"><span>P5 // READY-GATED PILOT</span><h1>Start controlled observation</h1><p>P4 is owner-attested READY. P5 freezes that record and starts a fresh local metrics window.</p></div><form id="run-start" class="run-form glass-card"><label>Pilot learner alias<input id="run-alias" maxlength="30" required placeholder="Alias only"></label><label>Optional target end date<input id="run-target" type="date"></label><label class="run-check"><input id="run-ack" type="checkbox" required><span>${esc(ACK)}</span></label><label class="run-check"><input id="run-assist" type="checkbox"><span>Allow bounded hints/worked guidance. Default OFF. No live AI tutor exists in this build.</span></label><button class="primary" type="submit">Start controlled run</button><p id="run-msg" class="run-note" role="status" aria-live="polite"></p></form>${controls()}</div>`;
function active(s){const w=metrics(),e=readiness(),ok=e.ready===true;return`<div class="page run-page"><div class="page-title"><span>P5 // RUN ACTIVE</span><h1>${esc(s.alias)}</h1><p>Started ${esc(new Date(s.startedAt).toLocaleString())}${s.targetEndDate?` · target ${esc(s.targetEndDate)}`:''}.</p></div><section id="run-current-readiness" class="run-status ${ok?'run-go':'run-hold'}"><small>CURRENT P4 GATE</small><h2>${ok?'READY':'HOLD — PAUSE PILOT'}</h2><p>${ok?'Current owner-attested prerequisites remain present.':'Readiness changed after start. Pause until P4 is restored.'}</p></section><section class="run-grid"><article class="glass-card"><small class="kicker">OBSERVATION</small><h2>${w?.observationDays??'—'} day${w?.observationDays===1?'':'s'}</h2><p>${w?.completeSevenDayWindow?'Seven-day window available.':'No seven-day retention claim yet.'}</p></article><article class="glass-card"><small class="kicker">ACTIVE LEARNING</small><h2>${w?.activeMinutes??'—'} min</h2><p>Conservative P3 measurement only.</p></article><article class="glass-card"><small class="kicker">ASSISTANCE AT START</small><h2>${s.assistanceEnabledAtStart?'ON':'OFF'}</h2></article></section><section class="glass-card"><div class="run-actions"><a class="primary" data-link href="/weekly-report">Weekly report →</a><button id="run-export">Export evidence</button><button id="run-end">End &amp; freeze run</button></div></section>${controls()}</div>`}
function ended(s){const f=s.finalSummary?.metrics;return`<div class="page run-page"><div class="page-title"><span>P5 // RUN ENDED</span><h1>${esc(s.alias)}</h1><p>Ended ${esc(new Date(s.endedAt).toLocaleString())}. Final evidence is local, not tamper-evident/audited analytics.</p></div><section class="run-grid"><article class="glass-card"><small class="kicker">OBSERVATION DAYS</small><h2>${f?.observationDays??'—'}</h2></article><article class="glass-card"><small class="kicker">ACTIVE MINUTES</small><h2>${f?.activeMinutes??'—'}</h2></article><article class="glass-card"><small class="kicker">LESSONS COMPLETED</small><h2>${f?.uniqueLessonsCompleted??'—'}</h2></article></section><section class="glass-card"><div class="run-actions"><button id="run-export">Export final evidence</button><a class="primary" data-link href="/pilot-readiness">P4 readiness record →</a></div></section>${controls()}</div>`}
function startRun(ev){ev.preventDefault();const msg=document.getElementById('run-msg'),e=readiness();if(!e.ready){msg.textContent='P4 readiness is no longer READY.';render();return}const alias=document.getElementById('run-alias').value.trim(),target=document.getElementById('run-target').value||null,ack=document.getElementById('run-ack').checked,assist=document.getElementById('run-assist').checked;if(!alias){msg.textContent='Enter a learner alias.';return}if(!ack){msg.textContent='Operator acknowledgement is required.';return}if(target&&target<new Date().toISOString().slice(0,10)){msg.textContent='Target end date cannot be in the past.';return}localStorage.removeItem(METRICS);window.KV_PILOT_METRICS?.sync?.();const startedAt=now(),s={schema:'kirthiverse.hitech.pilot-run.v1',status:'active',runId:uid(),alias:alias.slice(0,30),targetEndDate:target,startedAt,endedAt:null,operatorAcknowledgement:{statement:ACK,acknowledgedAt:startedAt,mode:'self-attestation',adultIdentityVerified:false,legalConsentVerified:false},assistanceEnabledAtStart:Boolean(assist),readinessAtStart:snapshotReadiness(),readinessAtEnd:null,finalSummary:null};save(KEY,s);setAssistance(assist);dispatchEvent(new CustomEvent('kv:pilot-run-started',{detail:{runId:s.runId,startedAt}}));render()}
function endRun(){const s=run();if(!s||s.status!=='active')return;window.KV_PILOT_METRICS?.sync?.();const endedAt=now();s.status='ended';s.endedAt=endedAt;s.readinessAtEnd=snapshotReadiness();s.finalSummary={capturedAt:endedAt,metrics:metrics(),readiness:s.readinessAtEnd,evidenceBoundary:{localOnly:true,tamperEvident:false,auditedResearchEvidence:false}};save(KEY,s);render()}
function resetRun(){if(!confirm('Reset only P5 run + P3 observation? P4 readiness and ordinary learning evidence remain.'))return;[KEY,METRICS].forEach(k=>localStorage.removeItem(k));render()}
function deleteAll(){const input=document.getElementById('run-delete-confirm'),msg=document.getElementById('run-delete-msg');if(input?.value!=='DELETE LOCAL DATA'){msg.textContent='Type the exact confirmation phrase.';return}if(!confirm('Delete all KirthiVerse local data in this browser? This cannot be undone.'))return;const lk=[];for(let i=0;i<localStorage.length;i++)lk.push(localStorage.key(i));lk.filter(Boolean).filter(k=>k.startsWith(PREFIX)).forEach(k=>localStorage.removeItem(k));const sk=[];for(let i=0;i<sessionStorage.length;i++)sk.push(sessionStorage.key(i));sk.filter(Boolean).filter(k=>k.startsWith(PREFIX)).forEach(k=>sessionStorage.removeItem(k));window.KV_LOCAL_DATA_DELETED=true;history.replaceState({},'', '/');const main=document.querySelector('main');if(main)main.innerHTML='<div class="page run-page"><div class="page-title"><span>LOCAL DATA DELETED</span><h1>KirthiVerse browser data cleared</h1><p>All current <code>kirthiverse.hitech.*</code> local/session records were removed. Unrelated origin storage was not touched. Reloading or using KirthiVerse again may create new empty runtime state.</p></div><a class="primary" href="/">Return to KirthiVerse →</a></div>'}
function bind(){document.getElementById('run-start')?.addEventListener('submit',startRun);document.getElementById('run-export')?.addEventListener('click',()=>download(evidence(),'kirthiverse-controlled-pilot-run-evidence.json'));document.getElementById('run-end')?.addEventListener('click',endRun);document.getElementById('run-reset')?.addEventListener('click',resetRun);const i=document.getElementById('run-delete-confirm'),b=document.getElementById('run-delete');i?.addEventListener('input',()=>b.disabled=i.value!=='DELETE LOCAL DATA');b?.addEventListener('click',deleteAll)}
function inject(){if(location.pathname==='/parent'&&unlocked()){const m=document.querySelector('main');if(m&&!m.querySelector('.run-parent-card')){const s=run(),e=readiness(),c=document.createElement('section');c.className='glass-card run-parent-card';c.innerHTML=`<small class="kicker">CONTROLLED PILOT RUN</small><h3>${s?.status==='active'?'Run active':s?.status==='ended'?'Run ended':e.ready?'Ready to start':'Blocked by P4 HOLD'}</h3><p>${e.ready?'P4 prerequisites are owner-attested READY.':'Complete/restore P4 readiness first.'}</p><a class="primary" data-link href="/pilot-run">Open controlled run →</a>`;m.appendChild(c)}}if(location.pathname==='/pilot-readiness'&&unlocked()&&readiness().ready){const m=document.querySelector('main');if(m&&!m.querySelector('.run-readiness-card')){const c=document.createElement('section');c.className='glass-card run-readiness-card run-go';c.innerHTML='<small class="kicker">NEXT GATE</small><h3>P4 owner-attested READY</h3><p>P5 can now start a fresh controlled observation window.</p><a class="primary" data-link href="/pilot-run">Open P5 controlled run →</a>';m.appendChild(c)}}}
function render(){inject();if(location.pathname!=='/pilot-run')return;const m=document.querySelector('main');if(!m)return;if(!unlocked()){m.innerHTML=parentLocked();return}const s=run(),e=readiness();m.innerHTML=!s?(e.ready?setup():hold(e)):s.status==='active'?active(s):ended(s);bind()}
addEventListener('kv:rendered',()=>queueMicrotask(render));render();window.KV_PILOT_RUN={version:'v1',route:'/pilot-run',localOnly:true,requiresReadiness:true,adultIdentityVerified:false,legalConsentVerified:false,externalReviewIndependentlyVerified:false,productionReady:false,state:()=>publicRun(),evidence};
})();