import assert from 'node:assert/strict';
import fs from 'node:fs';

const readJson=(path)=>JSON.parse(fs.readFileSync(path,'utf8'));
const manifest=readJson('docs/class6-pilot/CLASS6_COVERAGE_MANIFEST_V1.json');
const maths=readJson('docs/class6-pilot/MATHEMATICS_GANITA_PRAKASH_MAP_V1.json');
const mathAudit=readJson('docs/class6-pilot/MATHEMATICS_COMPLETION_AUDIT_V1.json');
const mathNeeds=Array.from({length:10},(_,i)=>readJson(`docs/class6-pilot/MATH_CH${i+1}_SCHOOL_NEEDS_VALIDATION_V1.json`));
const scienceMap=readJson('docs/class6-pilot/SCIENCE_CURIOSITY_MAP_V1.json');
const scienceAudit=readJson('docs/class6-pilot/SCIENCE_COMPLETION_AUDIT_V1.json');
const socialSource=readJson('docs/class6-pilot/SOCIAL_SCIENCE_SOURCE_RECONCILIATION_V1.json');
const socialMap=readJson('docs/class6-pilot/SOCIAL_SCIENCE_CURRICULUM_MAPPING_V1.json');

assert.equal(manifest.schemaVersion,'1.5.0');assert.equal(manifest.pilot.board,'CBSE');assert.equal(manifest.pilot.class,6);assert.equal(manifest.pilot.canonicalRepository,'ssakthivel02/kirthiverse-hitech');assert.equal(manifest.pilot.lastReconciledMain,'c091180259a354871fdfdb4704bf2abfa912c21e');
const byId=Object.fromEntries(manifest.subjects.map(x=>[x.id,x]));assert.equal(manifest.subjects.length,11);assert.equal(Object.keys(byId).length,11);
const science=byId.science;assert.equal(science.status,'SCIENCE_COMPLETE');assert.equal(science.completionClaim,true);assert.equal(science.mappedChapterCount,12);assert.equal(science.implementedChapterCount,12);assert.equal(science.schoolNeedsValidatedChapterCount,12);assert.equal(scienceAudit.decision,'SCIENCE_COMPLETE');assert.equal(scienceMap.chapters.length,12);assert.ok(scienceMap.chapters.every(x=>x.status==='KIKI_TEACHING_SLICE_COMPLETE'));assert.match(science.completionBoundary,/not live-school efficacy/i);
const mathematics=byId.mathematics;assert.equal(mathematics.status,'MATHEMATICS_COMPLETE');assert.equal(mathematics.completionClaim,true);assert.equal(mathematics.completionAudit,'docs/class6-pilot/MATHEMATICS_COMPLETION_AUDIT_V1.json');assert.equal(mathAudit.decision,'MATHEMATICS_COMPLETE');assert.match(mathematics.completionBoundary,/not live-school efficacy/i);assert.equal(maths.schemaVersion,'1.11.0');assert.equal(maths.chapters.length,10);
const implementedMath=maths.chapters.filter(x=>x.status==='KIKI_TEACHING_SLICE_COMPLETE');const pendingMath=maths.chapters.filter(x=>x.status==='MAPPED_NOT_YET_IMPLEMENTED');
assert.deepEqual(implementedMath.map(x=>x.chapter),[1,2,3,4,5,6,7,8,9,10]);assert.equal(pendingMath.length,0);
assert.equal(mathematics.mappedChapterCount,10);assert.equal(mathematics.implementedChapterCount,10);assert.equal(mathematics.remainingMappedChapterCount,0);assert.equal(mathematics.schoolNeedsValidatedChapterCount,10);
for(const chapter of [1,2,3,4,5,6,7,8,9,10])assert.equal(maths[`chapter${chapter}CompletionEvidence`]?.schoolNeedsValidationPresent,true,`Chapter ${chapter} school-needs evidence must be present`);
assert.equal(maths.chapter9CompletionEvidence?.schoolNeedsValidationArtifact,'docs/class6-pilot/MATH_CH9_SCHOOL_NEEDS_VALIDATION_V1.json');assert.equal(maths.chapter9CompletionEvidence?.startupRequestCeilingPreserved,true);assert.equal(maths.chapter9CompletionEvidence?.runtimeCarrier,'data/class6-math-pilot.js');assert.equal(maths.chapter9CompletionEvidence?.sourceOfTruth,'data/class6-math-ch9.js');
assert.equal(maths.chapter10CompletionEvidence?.schoolNeedsValidationRequired,true);assert.equal(maths.chapter10CompletionEvidence?.schoolNeedsValidationPresent,true);assert.equal(maths.chapter10CompletionEvidence?.schoolNeedsValidationArtifact,'docs/class6-pilot/MATH_CH10_SCHOOL_NEEDS_VALIDATION_V1.json');assert.equal(maths.chapter10CompletionEvidence?.startupRequestCeilingPreserved,true);assert.equal(maths.chapter10CompletionEvidence?.runtimeCarrier,'data/class6-math-pilot.js');assert.equal(maths.chapter10CompletionEvidence?.sourceOfTruth,'data/class6-math-ch10.js');
for(const artifact of mathNeeds){assert.equal(artifact.validationType,'SYNTHETIC_SCHOOL_LEARNING_NEEDS_READINESS');assert.equal(artifact.schoolOverlay.liveSchoolEvidenceCollected,false);assert.equal(artifact.schoolOverlay.schoolSpecificPacingClaimed,false);assert.equal(artifact.scenarios.length,8);}
assert.equal(mathNeeds.at(-1).validationId,'KVS-CBSE6-MATH-CH10-SCHOOL-NEEDS-V1');assert.equal(mathNeeds.flatMap(x=>x.scenarios).length,80);
const social=byId['social-science'];assert.equal(social.status,'SOURCE_BASELINE_RECONCILED_NEXT');assert.equal(social.sourceReconciliation,'docs/class6-pilot/SOCIAL_SCIENCE_SOURCE_RECONCILIATION_V1.json');assert.equal(social.curriculumMap,'docs/class6-pilot/SOCIAL_SCIENCE_CURRICULUM_MAPPING_V1.json');assert.equal(social.officialChapterLinkCountVerified,12);assert.equal(social.mappedChapterCount,14);assert.equal(social.chapterTitlesVerified,true);assert.equal(social.implementedChapterCount,0);assert.notEqual(social.completionClaim,true);
assert.equal(socialSource.decision,'SOCIAL_SCIENCE_MAPPING_REQUIRES_14_CHAPTER_BASELINE');assert.equal(socialSource.officialSource.provider,'NCERT');assert.equal(socialSource.officialSource.titleVerified,true);assert.equal(socialSource.officialSource.publicationCode,'0681');assert.equal(socialSource.officialSource.earlierRenderedChapterLinkCount,12);assert.equal(socialSource.officialSource.currentWorkingChapterCount,14);assert.equal(socialSource.officialSource.chapterContentExtracted,false);assert.equal(socialSource.officialSource.chapterTitlesVerified,true);assert.ok(socialSource.mappingArtifact.endsWith('SOCIAL_SCIENCE_CURRICULUM_MAPPING_V1.json'));assert.equal(socialSource.mappingStatus.chapterCount,14);assert.equal(socialSource.mappingStatus.implementedChapterCount,0);assert.notEqual(socialSource.mappingStatus.completionClaim,true);assert.ok(socialSource.gatesBeforeImplementation.length>=7);
assert.equal(socialMap.decision,'SOCIAL_SCIENCE_14_CHAPTER_MAPPING_BASELINE');assert.equal(socialMap.officialSource.currentChapterCountForMapping,14);assert.equal(socialMap.chapters.length,14);assert.deepEqual(socialMap.chapters.map(x=>x.chapter),[1,2,3,4,5,6,7,8,9,10,11,12,13,14]);assert.equal(socialMap.chapters[0].title,'Locating Places on the Earth');assert.equal(socialMap.chapters[12].title,'The Value of Work');assert.equal(socialMap.chapters[13].title,'Economic Activities Around Us');assert.equal(socialMap.implementationStatus.implementedChapterCount,0);assert.notEqual(socialMap.implementationStatus.completionClaim,true);
assert.equal(manifest.priorityDecision.selectedLane,'class6-coverage');assert.equal(manifest.priorityDecision.selectedSubject,'social-science');assert.equal(manifest.priorityDecision.selectedNextChapter,null);assert.equal(manifest.priorityDecision.selectedNextChapterTitle,null);assert.equal(manifest.priorityDecision.selectedNextTask,'Social Science Provenance, Rights & School-Overlay Reconciliation');assert.equal(manifest.priorityDecision.requiresFreshConcurrencyCheckBeforeWrite,true);
for(const id of ['english','language-2','language-3','social-science','life-skills-aptitude','computer-science','health-physical-education','work-education','art-education'])assert.notEqual(byId[id].completionClaim,true,`${id} must not claim completion`);
assert.equal(manifest.safety.unrestrictedChildChat,false);assert.equal(manifest.safety.microphoneCapture,false);assert.equal(manifest.safety.externalLearnerPrompts,false);assert.equal(manifest.safety.childFacingCloudAI,false);assert.equal(manifest.safety.realChildCloudPersistence,false);assert.equal(manifest.legacyPolicy.oldReposAreReadOnlyDonors,true);assert.equal(manifest.legacyPolicy.bulkCopyAllowed,false);assert.equal(manifest.legacyPolicy.reconcileOnlyIfMissing,true);assert.equal(manifest.legacyPolicy.sourceAndRightsReviewRequired,true);
console.log('Class 6 coverage reconciliation: PASS');
