import assert from 'node:assert/strict';
import fs from 'node:fs';

const rec=JSON.parse(fs.readFileSync('docs/class6-pilot/SOCIAL_SCIENCE_CH7_SOURCE_TOPIC_RECONCILIATION_V1.json','utf8'));
const map=JSON.parse(fs.readFileSync('docs/class6-pilot/SOCIAL_SCIENCE_CURRICULUM_MAPPING_V1.json','utf8'));

assert.equal(rec.schemaVersion,'1.0.0');
assert.equal(rec.reconciliationId,'KVS-CBSE6-SOC-CH7-SOURCE-TOPIC-V1');
assert.equal(rec.subject,'Social Science');
assert.equal(rec.class,6);
assert.equal(rec.board,'CBSE');
assert.equal(rec.curriculumSession,'2026-27');
assert.equal(rec.book,'Exploring Society: India and Beyond');
assert.equal(rec.chapter,7);
assert.equal(rec.chapterTitle,'India’s Cultural Roots');
assert.equal(rec.decision,'CHAPTER_7_SOURCE_TOPIC_BOUNDARY_RECONCILED');
assert.equal(rec.canonicalSource.provider,'NCERT');
assert.equal(rec.canonicalSource.publicationCode,'0681');
assert.equal(rec.canonicalSource.chapterNumber,7);
assert.equal(rec.canonicalSource.chapterTitleVerified,'India’s Cultural Roots');
assert.equal(rec.canonicalSource.chapterTextCopied,false);
assert.equal(rec.canonicalSource.exerciseQuestionsCopied,false);
assert.equal(rec.canonicalSource.sacredTextQuotationsCopied,false);
assert.equal(rec.canonicalSource.illustrationsCopied,false);
assert.equal(rec.currentStructureCorroboration.session,'2026-27');
assert.equal(rec.currentStructureCorroboration.chapterCount,14);
assert.equal(rec.currentStructureCorroboration.chapter7Title,'India’s Cultural Roots');
assert.equal(rec.reconciledTopicBoundary.length,4);
assert.deepEqual(rec.reconciledTopicBoundary.map(x=>x.topicId),['TOPIC-SOC6-07-01','TOPIC-SOC6-07-02','TOPIC-SOC6-07-03','TOPIC-SOC6-07-04']);
assert.ok(rec.reconciledTopicBoundary.every(x=>x.independentAuthoringAllowed===true));
assert.ok(rec.reconciledTopicBoundary.every(x=>x.implementationStatus==='BOUNDARY_RECONCILED_NOT_IMPLEMENTED'));
assert.equal(rec.rightsAndSchoolBoundary.schoolUse,'validation-context overlay only');
assert.equal(rec.rightsAndSchoolBoundary.schoolSpecificPacingClaimed,false);
assert.equal(rec.rightsAndSchoolBoundary.liveSchoolEvidenceCollected,false);
assert.equal(rec.rightsAndSchoolBoundary.realChildDataCollected,false);
assert.equal(rec.rightsAndSchoolBoundary.learnerBeliefDisclosureRequired,false);
assert.equal(rec.implementationGate.topicCount,4);
assert.equal(rec.implementationGate.lessonImplementationAllowedAfterMerge,true);
assert.equal(rec.implementationGate.assessmentImplementationAllowedAfterMerge,true);
assert.equal(rec.implementationGate.schoolNeedsValidationRequiredAfterTeachingSlice,true);
assert.equal(rec.implementationGate.runtimeChangeRequiredByThisReconciliation,false);
assert.equal(rec.implementationGate.completionClaim,false);

const allText=JSON.stringify(rec).toLowerCase();
for(const required of ['vedas','oral','upanishad','vedanta','yoga','charvaka','buddhism','jainism','folk','tribal'])assert.ok(allText.includes(required),`missing Chapter 7 boundary: ${required}`);
for(const forbidden of ['learner belief disclosure required": true','real child data collected": true','religion disclosure required": true','caste disclosure required": true','conversion-oriented activity required','devotional performance required'])assert.ok(!allText.includes(forbidden),`forbidden Chapter 7 claim: ${forbidden}`);
const exclusions=(rec.excludedOrDeferredBoundary||[]).join(' ').toLowerCase();
assert.match(exclusions,/prayer|chanting|meditation|ritual|worship|devotional|conversion/);
assert.match(exclusions,/religion|caste|sect|tribe|community|ancestry/);
assert.match(exclusions,/true, false, superior, inferior|true.*false.*superior.*inferior/);
assert.match(exclusions,/metaphysical|theological/);
assert.match(exclusions,/modern religious|caste|communal|territorial|party-political/);

const ch7=map.chapters.find(x=>x.chapter===7);
assert.equal(ch7.title,'India’s Cultural Roots');
assert.equal(ch7.status,'MAPPED_NOT_YET_IMPLEMENTED');
assert.equal(ch7.topicCount,4);
assert.equal(ch7.sourceTopicReconciliationArtifact,'docs/class6-pilot/SOCIAL_SCIENCE_CH7_SOURCE_TOPIC_RECONCILIATION_V1.json');
assert.equal(ch7.schoolNeedsValidationRequired,true);
assert.equal(ch7.schoolNeedsValidationPresent,false);
assert.equal(map.implementationStatus.implementedChapterCount,6);
assert.equal(map.implementationStatus.schoolNeedsValidatedChapterCount,6);
assert.equal(map.implementationStatus.completionClaim,false);

console.log('CLASS6_SOCIAL_SCIENCE_CH7_RECONCILIATION_PASS topics=4 teaching=pending schoolNeeds=pending beliefDisclosure=false');
