import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const lessonIds=['math.cbse6.ganita-prakash.ch4.collect-organise-frequency.v1','math.cbse6.ganita-prakash.ch4.pictographs-keys.v1','math.cbse6.ganita-prakash.ch4.bar-graphs-scale.v1'];
const map=JSON.parse(fs.readFileSync('docs/class6-pilot/MATHEMATICS_GANITA_PRAKASH_MAP_V1.json','utf8'));assert.equal(map.schemaVersion,'1.11.0');assert.equal(map.chapters[3].chapter,4);assert.equal(map.chapters[3].title,'Data Handling and Presentation');assert.equal(map.chapters[3].status,'KIKI_TEACHING_SLICE_COMPLETE');assert.equal(map.chapter4Topics.length,3);assert.ok(map.chapter4Topics.every(x=>x.status==='END_TO_END_PILOT_IMPLEMENTED'));assert.equal(map.chapter4CompletionEvidence.lessonCount,3);assert.equal(map.chapter4CompletionEvidence.assessmentCount,15);assert.equal(map.chapter4CompletionEvidence.lazyAssessmentLoadingRequired,true);assert.equal(map.chapter4CompletionEvidence.startupRequestCeilingPreserved,true);assert.equal(map.chapter4CompletionEvidence.schoolNeedsValidationRequired,true);assert.equal(map.chapter4CompletionEvidence.schoolNeedsValidationPresent,true);assert.equal(map.chapter4CompletionEvidence.schoolNeedsValidationArtifact,'docs/class6-pilot/MATH_CH4_SCHOOL_NEEDS_VALIDATION_V1.json');assert.ok(fs.existsSync(map.chapter4CompletionEvidence.schoolNeedsValidationArtifact));
const sandbox={window:{KV_LESSONS:[],KV_ASSESSMENTS:[]}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('data/class6-math-ch4.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('data/class6-math-ch4-assessments.js','utf8'),sandbox);const lessons=sandbox.window.KV_LESSONS,assessments=sandbox.window.KV_ASSESSMENTS;assert.equal(lessons.length,3);assert.deepEqual([...lessons.map(x=>x.id)].sort(),[...lessonIds].sort());assert.equal(new Set(lessons.map(x=>x.topicId)).size,3);for(const lesson of lessons){assert.equal(lesson.subject,'Mathematics');assert.equal(lesson.board,'CBSE');assert.equal(lesson.classLevel,6);assert.equal(lesson.book,'Ganita Prakash');assert.equal(lesson.chapter,4);assert.equal(lesson.chapterTitle,'Data Handling and Presentation');assert.equal(lesson.ageBand,'11-13');assert.ok(lesson.learningObjective.length>40);assert.ok(lesson.content.length>300);assert.ok(lesson.workedExample.length>100);assert.ok(Array.isArray(lesson.sourceRefs)&&lesson.sourceRefs.length>=2);assert.match(lesson.rightsStatus,/ORIGINAL/);assert.notEqual(lesson.schoolMappingStatus,'VERIFIED');for(const f of ['objective','intro','priorKnowledge','visualIdea','misconceptionCheck','recap','parentPrompt'])assert.ok(lesson.kikiTeaching?.[f]);for(const f of ['trigger','strategy','masteryEvidence'])assert.ok(lesson.remediation?.[f])}
assert.equal(assessments.length,15);const expectedIds=Array.from({length:15},(_,i)=>`KV-CBSE6-MATH-${String(i+46).padStart(4,'0')}`);assert.deepEqual(assessments.map(x=>x.stableAssessmentId),expectedIds);assert.equal(new Set(assessments.map(x=>x.stableAssessmentId)).size,15);for(const lessonId of lessonIds){const attached=assessments.filter(x=>x.lessonId===lessonId);assert.equal(attached.length,5);for(const type of ['multiple_choice','reasoning','worked_challenge','short_answer','mastery_check'])assert.ok(attached.some(x=>x.assessmentType===type));}
const allText=JSON.stringify({lessons,assessments,map:map.chapter4Topics}).toLowerCase();for(const required of ['raw data','tally','frequency','pictograph','key','bar graph','scale','baseline'])assert.ok(allText.includes(required));assert.ok(allText.includes('in this dataset'));assert.ok(allText.includes('misleading')||allText.includes('exaggerat'));
const runtimeSandbox={window:{KV_LESSONS:[]}};vm.createContext(runtimeSandbox);vm.runInContext(fs.readFileSync('data/class6-math-ch3-4-runtime.js','utf8'),runtimeSandbox);assert.equal(runtimeSandbox.window.KV_LESSONS.length,15,'approved Chapters 3-7 runtime bundle must expose fifteen lessons');assert.ok(lessonIds.every(id=>runtimeSandbox.window.KV_LESSONS.some(x=>x.id===id)));assert.equal(new Set(runtimeSandbox.window.KV_LESSONS.map(x=>x.id)).size,15);
const entry=fs.readFileSync('p0-entry-v1.js','utf8');for(const asset of ['data/class6-math-ch3-4-runtime.js','data/class6-math-ch4-assessments.js','data/class6-math-ch9-assessments.js','data/class6-math-ch10-assessments.js'])assert.ok(entry.includes(asset));assert.ok(entry.includes('ch(?:2|3|4|5|6|7|8|9|10)\\.'));assert.ok(!entry.includes("/^\\/lesson\\/math\\./"));const baseChunk=entry.slice(entry.indexOf('const mathBaseFiles'),entry.indexOf('const loadClass6MathPilot'));assert.ok(baseChunk.includes('data/class6-math-ch3-4-runtime.js'));assert.ok(!baseChunk.includes('data/class6-math-ch4.js'));assert.ok(!baseChunk.includes('data/class6-math-ch4-assessments.js'));assert.ok(!baseChunk.includes('data/class6-math-ch9.js'));assert.ok(!baseChunk.includes('data/class6-math-ch10.js'));assert.ok(!baseChunk.includes('data/class6-math-ch10-assessments.js'));
const sw=fs.readFileSync('sw-v30.js','utf8');assert.match(sw,/kirthiverse-preview-v45/);for(const asset of ['/data/class6-math-ch3-4-runtime.js','/data/class6-math-ch4-assessments.js','/data/class6-math-ch9-assessments.js','/data/class6-math-ch10-assessments.js'])assert.ok(sw.includes(asset));const index=fs.readFileSync('index.html','utf8');assert.ok(index.includes("I’m Kiki, your KirthiVerse guide."));assert.ok(index.includes('microphone:false'));assert.ok(index.includes('recording:false'));assert.ok(index.includes('speechRecognition:false'));
console.log(`CLASS6_MATH_CH4_PASS topics=${map.chapter4Topics.length} lessons=${lessons.length} assessments=${assessments.length} schoolNeeds=${map.chapter4CompletionEvidence.schoolNeedsValidationPresent}`);