import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const lessonIds=['science.cbse6.curiosity.ch3.food-diversity-nutrients.v1','science.cbse6.curiosity.ch3.balanced-meals-routines.v1','science.cbse6.curiosity.ch3.food-information-hygiene.v1'];
const map=JSON.parse(fs.readFileSync('docs/class6-pilot/SCIENCE_CURIOSITY_MAP_V1.json','utf8'));
assert.equal(map.chapters.length,12);assert.equal(map.chapters[2].title,'Mindful Eating: A Path to a Healthy Body');assert.equal(map.chapters[2].status,'KIKI_TEACHING_SLICE_COMPLETE');assert.equal(map.chapter3Topics.length,3);assert.ok(map.chapter3Topics.every(x=>x.status==='END_TO_END_PILOT_IMPLEMENTED'));assert.ok(map.chapter3Topics.every(x=>Array.isArray(x.competencies)&&x.competencies.length>=3));assert.ok(map.chapter3Topics.every(x=>Array.isArray(x.misconceptions)&&x.misconceptions.length>=3));assert.ok(map.chapter3Topics.every(x=>Array.isArray(x.safetyBoundary)&&x.safetyBoundary.length>=3));assert.equal(map.chapter3CompletionEvidence.lessonCount,3);assert.equal(map.chapter3CompletionEvidence.assessmentCount,15);assert.equal(map.chapter3CompletionEvidence.childNutritionSafetyRequired,true);assert.equal(map.chapter3CompletionEvidence.status,'CHAPTER3_KIKI_TEACHING_SLICE_COMPLETE');assert.match(map.chapter3CompletionRule,/dieting|weight/i);assert.match(map.chapter3CompletionRule,/allergy self-testing/i);assert.match(map.completionRule,/all twelve/i);
const sandbox={window:{KV_LESSONS:[],KV_ASSESSMENTS:[]}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('data/class6-science-ch3.js','utf8'),sandbox);vm.runInContext(fs.readFileSync('data/class6-science-ch3-assessments.js','utf8'),sandbox);const lessons=sandbox.window.KV_LESSONS,assessments=sandbox.window.KV_ASSESSMENTS;assert.equal(lessons.length,3);assert.deepEqual([...lessons.map(x=>x.id)].sort(),[...lessonIds].sort());assert.equal(new Set(lessons.map(x=>x.topicId)).size,3);
for(const lesson of lessons){assert.equal(lesson.subject,'Science');assert.equal(lesson.board,'CBSE');assert.equal(lesson.classLevel,6);assert.equal(lesson.book,'Curiosity');assert.equal(lesson.chapter,3);assert.equal(lesson.ageBand,'11-13');assert.ok(lesson.learningObjective.length>60);assert.ok(lesson.content.length>600);assert.ok(lesson.workedExample.length>180);assert.ok(Array.isArray(lesson.sourceRefs)&&lesson.sourceRefs.length>=2);assert.match(lesson.rightsStatus,/ORIGINAL/);for(const field of ['objective','intro','priorKnowledge','visualIdea','misconceptionCheck','recap','parentPrompt'])assert.ok(lesson.kikiTeaching?.[field]);for(const field of ['trigger','strategy','masteryEvidence'])assert.ok(lesson.remediation?.[field]);}
assert.equal(assessments.length,15);assert.equal(new Set(assessments.map(x=>x.stableAssessmentId)).size,15);assert.deepEqual(assessments.map(x=>x.stableAssessmentId),Array.from({length:15},(_,i)=>`KV-CBSE6-SCI-${String(i+31).padStart(4,'0')}`));for(const lessonId of lessonIds){const attached=assessments.filter(x=>x.lessonId===lessonId);assert.equal(attached.length,5);assert.ok(attached.some(x=>x.assessmentType==='reasoning'));assert.ok(attached.some(x=>x.assessmentType==='mastery_check'));}
const allText=JSON.stringify({lessons,assessments,map:map.chapter3Topics}).toLowerCase();for(const required of ['food diversity','hydration','hygiene','marketing claim','trusted adult','qualified healthcare'])assert.ok(allText.includes(required));assert.ok(allText.includes('no calorie')||allText.includes('without calorie')||allText.includes('calorie target'));assert.ok(allText.includes('weight-loss')||allText.includes('weight control'));assert.ok(allText.includes('allergy self-testing')||allText.includes('should not test suspected allergies'));assert.ok(allText.includes('supplement')&&allText.includes('treatment'));assert.ok(!/\b(?:800|1000|1200|1500|1800|2000)\s*(?:kcal|calories)\b/i.test(allText));assert.ok(!/\bbmi\s*(?:target|goal|score)\b/i.test(allText));
const entry=fs.readFileSync('p0-entry-v1.js','utf8');for(const asset of ['data/class6-science-ch3.js','data/class6-science-ch3-assessments.js'])assert.ok(entry.includes(asset));assert.match(entry,/datasetKey:'class6SciencePilot'/);assert.match(entry,/CBSE6-SCI-CH6-1/);const sw=fs.readFileSync('sw-v30.js','utf8');assert.match(sw,/kirthiverse-preview-v39/);for(const asset of ['/data/class6-science-ch3.js','/data/class6-science-ch3-assessments.js'])assert.ok(sw.includes(asset));const index=fs.readFileSync('index.html','utf8');assert.ok(index.includes("I’m Kiki, your KirthiVerse guide."));assert.ok(index.includes('microphone:false'));assert.ok(index.includes('recording:false'));assert.ok(index.includes('speechRecognition:false'));console.log(`CLASS6_SCIENCE_CH3_PASS topics=${map.chapter3Topics.length} lessons=${lessons.length} assessments=${assessments.length} childNutritionSafety=${map.chapter3CompletionEvidence.childNutritionSafetyRequired}`);
