import assert from 'node:assert/strict';
import fs from 'node:fs';

const rec=JSON.parse(fs.readFileSync('docs/class6-pilot/SOCIAL_SCIENCE_CH5_SOURCE_TOPIC_RECONCILIATION_V1.json','utf8'));
const map=JSON.parse(fs.readFileSync('docs/class6-pilot/SOCIAL_SCIENCE_CURRICULUM_MAPPING_V1.json','utf8'));

assert.equal(rec.schemaVersion,'1.0.0');
assert.equal(rec.reconciliationId,'KVS-CBSE6-SOC-CH5-SOURCE-TOPIC-V1');
assert.equal(rec.subject,'Social Science');
assert.equal(rec.class,6);
assert.equal(rec.board,'CBSE');
assert.equal(rec.curriculumSession,'2026-27');
assert.equal(rec.book,'Exploring Society: India and Beyond');
assert.equal(rec.chapter,5);
assert.equal(rec.chapterTitle,'India, That Is Bharat');
assert.equal(rec.decision,'CHAPTER_5_SOURCE_TOPIC_BOUNDARY_RECONCILED');
assert.equal(rec.canonicalSource.provider,'NCERT');
assert.equal(rec.canonicalSource.publicationCode,'0681');
assert.equal(rec.canonicalSource.chapterNumber,5);
assert.equal(rec.canonicalSource.chapterTitleVerified,'India, That Is Bharat');
assert.equal(rec.canonicalSource.chapterTextCopied,false);
assert.equal(rec.canonicalSource.exerciseQuestionsCopied,false);
assert.equal(rec.canonicalSource.illustrationsCopied,false);
assert.equal(rec.currentStructureCorroboration.session,'2026-27');
assert.equal(rec.currentStructureCorroboration.chapterCount,14);
assert.equal(rec.currentStructureCorroboration.chapter5Title,'India, That Is Bharat');
assert.equal(rec.reconciledTopicBoundary.length,4);
assert.deepEqual(rec.reconciledTopicBoundary.map(x=>x.topicId),['TOPIC-SOC6-05-01','TOPIC-SOC6-05-02','TOPIC-SOC6-05-03','TOPIC-SOC6-05-04']);
assert.ok(rec.reconciledTopicBoundary.every(x=>x.independentAuthoringAllowed===true));
assert.ok(rec.reconciledTopicBoundary.every(x=>x.implementationStatus==='BOUNDARY_RECONCILED_NOT_IMPLEMENTED'));
assert.equal(rec.rightsAndSchoolBoundary.schoolUse,'validation-context overlay only');
assert.equal(rec.rightsAndSchoolBoundary.schoolSpecificPacingClaimed,false);
assert.equal(rec.rightsAndSchoolBoundary.liveSchoolEvidenceCollected,false);
assert.equal(rec.rightsAndSchoolBoundary.realChildDataCollected,false);
assert.equal(rec.implementationGate.topicCount,4);
assert.equal(rec.implementationGate.lessonImplementationAllowedAfterMerge,true);
assert.equal(rec.implementationGate.assessmentImplementationAllowedAfterMerge,true);
assert.equal(rec.implementationGate.schoolNeedsValidationRequiredAfterTeachingSlice,true);
assert.equal(rec.implementationGate.runtimeChangeRequiredByThisReconciliation,false);
assert.equal(rec.implementationGate.completionClaim,false);

const ch5=map.chapters.find(x=>x.chapter===5);
assert.equal(map.schemaVersion,'1.14.0');
assert.equal(ch5.title,'India, That Is Bharat');
assert.equal(ch5.status,'KIKI_TEACHING_SLICE_COMPLETE');
assert.equal(ch5.topicCount,4);
assert.equal(ch5.sourceTopicReconciliationArtifact,'docs/class6-pilot/SOCIAL_SCIENCE_CH5_SOURCE_TOPIC_RECONCILIATION_V1.json');
assert.equal(ch5.schoolNeedsValidationRequired,true);
assert.equal(ch5.schoolNeedsValidationPresent,true);
assert.equal(ch5.schoolNeedsValidationArtifact,'docs/class6-pilot/SOCIAL_SCIENCE_CH5_SCHOOL_NEEDS_VALIDATION_V1.json');
assert.equal(map.implementationStatus.implementedChapterCount,5);
assert.equal(map.implementationStatus.schoolNeedsValidatedChapterCount,5);
assert.equal(map.implementationStatus.completionClaim,false);

const allText=JSON.stringify(rec).toLowerCase();
for(const required of ['geographical','historical names','sapta sindhava','jambudvipa','bharata','bharatavarsha','sindhu','india','constitutional']) assert.ok(allText.includes(required),`missing Chapter 5 boundary: ${required}`);
for(const forbidden of ['party politics advocacy','religion disclosure required','caste disclosure required','ancestry disclosure required','political preference required']) assert.ok(!allText.includes(forbidden),`forbidden Chapter 5 claim: ${forbidden}`);
const exclusions=(rec.excludedOrDeferredBoundary||[]).join(' ').toLowerCase();
assert.match(exclusions,/do not copy.*exercise/);
assert.match(exclusions,/party politics|territorial disputes|geopolitical claims/);
assert.match(exclusions,/religion, caste, community identity/);
assert.match(exclusions,/patriotic loyalty tests/);

console.log('CLASS6_SOCIAL_SCIENCE_CH5_RECONCILIATION_PASS topics=4 teaching=implemented schoolNeeds=validated');
