#!/usr/bin/env node
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),gen=path.join(root,'scripts','render-funding-evidence-brief.mjs'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'kv-p8-'));
const canonical=e=>[...e].sort((a,b)=>a.runId.localeCompare(b.runId)||a.sourceSha256.localeCompare(b.sourceSha256)).map(x=>({runId:x.runId,sourceSha256:x.sourceSha256,p6Status:x.p6Status,observationDays:x.observationDays,activeDays:x.activeDays,activeMinutes:x.activeMinutes,uniqueLessonsCompleted:x.uniqueLessonsCompleted,completeSevenDayWindow:x.completeSevenDayWindow,readyAtStart:x.readyAtStart,readyAtEnd:x.readyAtEnd}));
function pack(entries){const ce=canonical(entries),digest=crypto.createHash('sha256').update(JSON.stringify(ce)).digest('hex'),sum=k=>entries.reduce((n,e)=>n+(Number(e[k])||0),0),all=entries.every(e=>e.completeSevenDayWindow);return{packBuilder:'kirthiverse.p7.pilot-evidence-pack.v1',status:'VALIDATED_LOCAL_RUN_PACK',manifestSha256:digest,totals:{validatedRuns:entries.length,runsWithCompletedSevenDayObservation:entries.filter(e=>e.completeSevenDayWindow).length,sumActiveDaysAcrossRuns:sum('activeDays'),sumActiveMinutesAcrossRuns:Number(sum('activeMinutes').toFixed(1)),sumUniqueLessonCompletionsAcrossRuns:sum('uniqueLessonsCompleted')},entries,errors:[],warnings:[],claimGates:{structurallyValid:true,canDescribeAsPackOfValidatedLocalRuns:true,canDescribeAllRunsAsCompletedSevenDayObservation:all,canClaimRetention:false,canClaimLearningImprovement:false,canClaimCohortOutcome:false,canClaimComparativeEffectiveness:false,canClaimLegalCompliance:false,canClaimSafeguardingCertification:false,canClaimProductionReadiness:false,canClaimTamperEvidentAnalytics:false}}}
const e=(id,seven=true)=>({runId:id,sourceFile:id+'.json',sourceSha256:crypto.createHash('sha256').update(id).digest('hex'),p6Status:seven?'STRUCTURALLY_VALID_LOCAL_PILOT_EVIDENCE':'STRUCTURALLY_VALID_WITH_LIMITATIONS',observationDays:seven?7:2,activeDays:seven?4:1,activeMinutes:seven?50:12.5,uniqueLessonsCompleted:seven?3:1,completeSevenDayWindow:seven,readyAtStart:true,readyAtEnd:true});
function write(name,p){const f=path.join(tmp,name);fs.writeFileSync(f,JSON.stringify(p,null,2));return f}function run(p,args=[],code=0){const r=spawnSync(process.execPath,[gen,p,...args],{encoding:'utf8'});assert.equal(r.status,code,`${r.stdout}\n${r.stderr}`);return r}
const good=pack([e('A'),e('B')]),goodFile=write('good.json',good),md=path.join(tmp,'brief.md'),js=path.join(tmp,'brief.json');let r=run(goodFile,['--require-all-seven-day','--output',md,'--json-output',js]);assert.match(r.stdout,/2 independently P6-validated/);assert.match(fs.readFileSync(md,'utf8'),/Claims this evidence does not support/);const out=JSON.parse(fs.readFileSync(js,'utf8'));assert.equal(out.claimGates.canClaimRetention,false);assert.equal(out.claimGates.canDescribeAllRunsAsCompletedSevenDayObservation,true);
const mixed=pack([e('A'),e('C',false)]),mixedFile=write('mixed.json',mixed);r=run(mixedFile);assert.match(r.stdout,/1 of 2 validated runs contain completed seven-day observation windows/);run(mixedFile,['--require-all-seven-day'],1);
const tampered=pack([e('A'),e('B')]);tampered.entries[0].activeMinutes=999;run(write('tampered.json',tampered),[],1);
const badTotals=pack([e('A'),e('B')]);badTotals.totals.sumActiveMinutesAcrossRuns=999;run(write('bad-totals.json',badTotals),[],1);
const unsafe=pack([e('A')]);unsafe.claimGates.canClaimRetention=true;run(write('unsafe.json',unsafe),[],1);
const sensitive=pack([e('A')]);sensitive.entries[0].alias='Real Child';sensitive.manifestSha256=crypto.createHash('sha256').update(JSON.stringify(canonical(sensitive.entries))).digest('hex');run(write('sensitive.json',sensitive),[],1);
console.log('FUNDING_EVIDENCE_BRIEF_TEST_PASS');console.log(JSON.stringify({cases:6,status:out.status,manifestSha256:out.manifestSha256},null,2));
