#!/usr/bin/env node
import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),builder=path.join(root,'scripts','build-pilot-evidence-pack.mjs'),tmp=fs.mkdtempSync(path.join(os.tmpdir(),'kv-p7-'));const clone=x=>JSON.parse(JSON.stringify(x));
function src(id,start='2026-09-01T00:00:00.000Z',end='2026-09-08T00:05:00.000Z',days=7,complete=true){const ev={ready:true,status:'OWNER_ATTESTED_CONTROLLED_PILOT_READY',missing:[],unchecked:[],metricsAvailable:true,legalCertification:false,productionReady:false,externalReviewSelfVerified:false};const rec={schema:'kirthiverse.hitech.pilot-readiness.v1'};return{schema:'kirthiverse.hitech.controlled-pilot-run-evidence.v1',run:{status:'ended',runId:id,alias:'Pilot-'+id,startedAt:start,endedAt:end,operatorAcknowledgement:{mode:'self-attestation',acknowledgedAt:start,adultIdentityVerified:false,legalConsentVerified:false},readinessAtStart:{evaluation:clone(ev),record:clone(rec)},readinessAtEnd:{evaluation:clone(ev),record:clone(rec)},finalSummary:{metrics:{trackingStartedAt:start,observationDays:days,activeDays:Math.min(days,4),activeMinutes:45,uniqueLessonsCompleted:3,completeSevenDayWindow:complete,evidenceBoundary:{localOnly:true,networkTelemetry:false,tamperEvident:false,backfilledHistory:false,productionResearchEvidence:false}}}},evidenceBoundary:{localOnly:true,adultIdentityVerified:false,legalConsentVerified:false,externalReviewIndependentlyVerified:false,tamperEvident:false,auditedResearchEvidence:false,productionReady:false}}}
function w(name,p){const f=path.join(tmp,name);fs.writeFileSync(f,JSON.stringify(p,null,2));return f}function run(files,args=[],code=0){const r=spawnSync(process.execPath,[builder,...files,...args],{encoding:'utf8'});assert.equal(r.status,code,`${r.stdout}\n${r.stderr}`);return JSON.parse((r.stdout||r.stderr).trim())}function has(r,c){return r.errors?.some(x=>x.code===c)}
const a=w('a.json',src('A')),b=w('b.json',src('B'));const good=run([a,b]);assert.equal(good.status,'VALIDATED_LOCAL_RUN_PACK');assert.equal(good.totals.validatedRuns,2);assert.equal(good.claimGates.canDescribeAsPackOfValidatedLocalRuns,true);assert.equal(good.claimGates.canDescribeAllRunsAsCompletedSevenDayObservation,true);for(const k of ['canClaimRetention','canClaimLearningImprovement','canClaimCohortOutcome','canClaimLegalCompliance','canClaimProductionReadiness','canClaimTamperEvidentAnalytics'])assert.equal(good.claimGates[k],false);assert.match(good.manifestSha256,/^[a-f0-9]{64}$/);
const early=w('early.json',src('C','2026-09-07T00:00:00.000Z','2026-09-08T00:05:00.000Z',1,false));const mixed=run([a,early]);assert.equal(mixed.status,'VALIDATED_LOCAL_RUN_PACK_WITH_LIMITATIONS');assert.equal(mixed.claimGates.canDescribeAllRunsAsCompletedSevenDayObservation,false);const strict=run([a,early],['--require-seven-day-window-all'],1);assert.ok(has(strict,'SEVEN_DAY_WINDOW_REQUIRED_FOR_ALL'));
const dupId=w('dup-id.json',src('A'));assert.ok(has(run([a,dupId],[],1),'DUPLICATE_RUN_ID'));assert.ok(has(run([a,a],[],1),'DUPLICATE_SOURCE_DIGEST'));
const bad=src('D');bad.evidenceBoundary.productionReady=true;assert.ok(has(run([a,w('bad.json',bad)],[],1),'P6_VALIDATION_FAILED'));
const out=path.join(tmp,'pack.json'),withOut=run([a,b],['--output',out]);assert.equal(JSON.parse(fs.readFileSync(out,'utf8')).manifestSha256,withOut.manifestSha256);
console.log('PILOT_EVIDENCE_PACK_TEST_PASS');console.log(JSON.stringify({cases:6,runs:good.totals.validatedRuns,manifestSha256:good.manifestSha256,mixedStatus:mixed.status},null,2));
